import React, { useState } from 'react';
import { useData } from '../context/DataContext';
import { 
  Sparkles, Calendar, AlertTriangle, Lightbulb, CheckCircle, Brain, ArrowRight
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

// --- LIGHTWEIGHT CUSTOM MARKDOWN RENDERER ---
const parseBoldText = (text: string) => {
  const parts = text.split(/\*\*(.*?)\*\*/g);
  return parts.map((part, i) => i % 2 === 1 ? <strong key={i} className="font-extrabold text-slate-800 dark:text-white">{part}</strong> : part);
};

const MarkdownRenderer: React.FC<{ content: string }> = ({ content }) => {
  if (!content) return null;
  const lines = content.split('\n');
  
  return (
    <div className="space-y-2.5 text-slate-600 dark:text-slate-300 leading-relaxed text-sm">
      {lines.map((line, idx) => {
        const trimmed = line.trim();
        
        if (trimmed.startsWith('### ')) {
          return <h4 key={idx} className="text-sm font-bold text-slate-800 dark:text-white mt-4 uppercase tracking-wider">{trimmed.replace('### ', '')}</h4>;
        }
        if (trimmed.startsWith('## ')) {
          return <h3 key={idx} className="text-base font-bold text-slate-850 dark:text-slate-100 mt-5 border-b border-slate-100 dark:border-slate-800/60 pb-1.5">{trimmed.replace('## ', '')}</h3>;
        }
        if (trimmed.startsWith('# ')) {
          return <h2 key={idx} className="text-lg font-black text-slate-900 dark:text-white mt-6">{trimmed.replace('# ', '')}</h2>;
        }
        if (trimmed.startsWith('* ') || trimmed.startsWith('- ')) {
          return (
            <li key={idx} className="list-disc list-inside ml-2 pl-1">
              {parseBoldText(trimmed.substring(2))}
            </li>
          );
        }
        if (trimmed.startsWith('> ')) {
          return (
            <blockquote key={idx} className="border-l-4 border-brand-500 bg-brand-500/5 px-4 py-2.5 rounded-r-xl my-3 italic text-xs">
              {parseBoldText(trimmed.replace('> ', ''))}
            </blockquote>
          );
        }
        if (trimmed === '') {
          return <div key={idx} className="h-1.5" />;
        }
        return <p key={idx}>{parseBoldText(trimmed)}</p>;
      })}
    </div>
  );
};

export const AIReports: React.FC = () => {
  const { reports, generateAIReport } = useData();
  const [activeType, setActiveType] = useState<'daily' | 'weekly' | 'monthly'>('daily');
  const [selectedReportId, setSelectedReportId] = useState<string | null>(null);
  
  // Generator states
  const [showGenerator, setShowGenerator] = useState(false);
  const [genType, setGenType] = useState<'daily' | 'weekly' | 'monthly'>('daily');
  const [genDate, setGenDate] = useState(new Date().toISOString().split('T')[0]);
  const [generating, setGenerating] = useState(false);

  // Filter reports
  const filteredReports = reports.filter(r => r.type === activeType);
  const selectedReport = reports.find(r => r.id === selectedReportId) || filteredReports[0];

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setGenerating(true);
    try {
      const newReport = await generateAIReport(genType, genDate);
      setSelectedReportId(newReport.id);
      setActiveType(genType);
      setShowGenerator(false);
    } catch (err) {
      console.error(err);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-slate-800 dark:text-white flex items-center gap-2.5">
            <Sparkles className="w-8 h-8 text-indigo-500" /> AI Health Reports
          </h1>
          <p className="text-slate-500 dark:text-slate-400 mt-1">
            Read comprehensive habits analyses and weekly health audits generated by GPT.
          </p>
        </div>
        <button 
          onClick={() => setShowGenerator(true)}
          className="glass-btn-ai"
        >
          <Brain className="w-5 h-5" /> Generate Audit
        </button>
      </div>

      {/* Report Types Tabs */}
      <div className="flex bg-slate-100 dark:bg-slate-800/50 p-1.5 rounded-2xl border border-slate-200/40 dark:border-slate-700/20 max-w-md">
        {(['daily', 'weekly', 'monthly'] as const).map((type) => (
          <button
            key={type}
            onClick={() => { setActiveType(type); setSelectedReportId(null); }}
            className={`flex-1 text-sm capitalize py-2.5 rounded-xl font-bold transition-all ${
              activeType === type 
                ? 'bg-white dark:bg-slate-700 text-slate-850 dark:text-white shadow-sm' 
                : 'text-slate-400 hover:text-slate-600 dark:hover:text-slate-200'
            }`}
          >
            {type} Audits
          </button>
        ))}
      </div>

      {/* Main Split Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Side: Report List */}
        <div className="lg:col-span-4 glass-card p-4 space-y-3 h-[520px] overflow-y-auto">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider px-2 mb-2">Available Audits</h3>
          {filteredReports.length > 0 ? (
            filteredReports.map((r) => (
              <button
                key={r.id}
                onClick={() => setSelectedReportId(r.id)}
                className={`w-full text-left p-3.5 rounded-2xl border transition-all flex flex-col gap-1.5 ${
                  selectedReport?.id === r.id
                    ? 'bg-indigo-600 border-indigo-500 text-white shadow-lg shadow-indigo-500/15'
                    : 'bg-slate-50/50 dark:bg-slate-900/30 border-slate-200/40 dark:border-slate-800/50 hover:bg-slate-100/50 dark:hover:bg-slate-900/55'
                }`}
              >
                <div className="flex justify-between items-start w-full">
                  <span className={`text-xs font-bold ${selectedReport?.id === r.id ? 'text-indigo-200' : 'text-slate-400'}`}>
                    {new Date(r.date).toLocaleDateString('default', { day: 'numeric', month: 'short', year: 'numeric' })}
                  </span>
                  <span className={`text-[10px] font-black px-2 py-0.5 rounded-full ${
                    selectedReport?.id === r.id 
                      ? 'bg-white/25 text-white' 
                      : 'bg-indigo-500/10 text-indigo-500'
                  }`}>
                    Score: {r.score}
                  </span>
                </div>
                <div className={`font-bold text-sm truncate ${selectedReport?.id === r.id ? 'text-white' : 'text-slate-700 dark:text-slate-200'}`}>
                  {r.title}
                </div>
              </button>
            ))
          ) : (
            <div className="py-12 text-center text-slate-400 text-sm">
              No audits generated yet. Click "Generate Audit" to analyze your logs.
            </div>
          )}
        </div>

        {/* Right Side: Detailed Report View */}
        <div className="lg:col-span-8 glass-card p-6 min-h-[520px] flex flex-col justify-between">
          {selectedReport ? (
            <div className="space-y-6">
              {/* Report Header */}
              <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-slate-200/50 dark:border-slate-800/40 pb-4">
                <div>
                  <div className="flex items-center gap-2 text-xs text-indigo-500 dark:text-indigo-400 font-bold uppercase tracking-wider">
                    <Sparkles className="w-3.5 h-3.5" /> AI Health Coach
                  </div>
                  <h2 className="text-xl font-black text-slate-800 dark:text-white mt-1">{selectedReport.title}</h2>
                </div>

                <div className="flex items-center gap-4">
                  <div className="flex items-center gap-1.5 text-xs text-slate-400 font-medium">
                    <Calendar className="w-4 h-4" />
                    {new Date(selectedReport.date).toLocaleDateString('default', { day: 'numeric', month: 'short', year: 'numeric' })}
                  </div>
                  <div className="bg-brand-500 text-white font-extrabold px-3.5 py-1.5 rounded-2xl text-sm shadow-md shadow-brand-500/10">
                    Score: {selectedReport.score}/100
                  </div>
                </div>
              </div>

              {/* Stats Summary Panel (if present) */}
              {selectedReport.statsSummary && (
                <div className="grid grid-cols-2 md:grid-cols-6 gap-3 text-center">
                  {selectedReport.statsSummary.weightChange !== undefined && (
                    <div className="bg-slate-50/50 dark:bg-slate-900/30 p-2.5 rounded-xl border border-slate-200/15 dark:border-slate-800/10">
                      <div className="text-xs text-slate-400">Weight</div>
                      <div className={`text-sm font-black mt-0.5 ${selectedReport.statsSummary.weightChange <= 0 ? 'text-emerald-500' : 'text-rose-500'}`}>
                        {selectedReport.statsSummary.weightChange} kg
                      </div>
                    </div>
                  )}
                  {selectedReport.statsSummary.avgCalories !== undefined && (
                    <div className="bg-slate-50/50 dark:bg-slate-900/30 p-2.5 rounded-xl border border-slate-200/15 dark:border-slate-800/10">
                      <div className="text-xs text-slate-400">Avg Cals</div>
                      <div className="text-sm font-black text-slate-755 dark:text-slate-200 mt-0.5">
                        {selectedReport.statsSummary.avgCalories}
                      </div>
                    </div>
                  )}
                  {selectedReport.statsSummary.avgProtein !== undefined && (
                    <div className="bg-slate-50/50 dark:bg-slate-900/30 p-2.5 rounded-xl border border-slate-200/15 dark:border-slate-800/10">
                      <div className="text-xs text-slate-400">Protein</div>
                      <div className="text-sm font-black text-indigo-500 mt-0.5">
                        {selectedReport.statsSummary.avgProtein}g
                      </div>
                    </div>
                  )}
                  {selectedReport.statsSummary.avgWater !== undefined && (
                    <div className="bg-slate-50/50 dark:bg-slate-900/30 p-2.5 rounded-xl border border-slate-200/15 dark:border-slate-800/10">
                      <div className="text-xs text-slate-400">Water</div>
                      <div className="text-sm font-black text-sky-500 mt-0.5">
                        {(selectedReport.statsSummary.avgWater / 1000).toFixed(1)}L
                      </div>
                    </div>
                  )}
                  {selectedReport.statsSummary.avgSleep !== undefined && (
                    <div className="bg-slate-50/50 dark:bg-slate-900/30 p-2.5 rounded-xl border border-slate-200/15 dark:border-slate-800/10">
                      <div className="text-xs text-slate-400">Sleep</div>
                      <div className="text-sm font-black text-purple-500 mt-0.5">
                        {selectedReport.statsSummary.avgSleep}h
                      </div>
                    </div>
                  )}
                  {selectedReport.statsSummary.avgSteps !== undefined && (
                    <div className="bg-slate-50/50 dark:bg-slate-900/30 p-2.5 rounded-xl border border-slate-200/15 dark:border-slate-800/10">
                      <div className="text-xs text-slate-400">Steps</div>
                      <div className="text-sm font-black text-amber-500 mt-0.5">
                        {selectedReport.statsSummary.avgSteps.toLocaleString()}
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* Markdown Content */}
              <div className="space-y-4">
                <MarkdownRenderer content={selectedReport.summary} />
                
                {/* Structured Sections */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4">
                  {/* Positives */}
                  <div className="space-y-3">
                    <h3 className="text-sm font-extrabold text-emerald-500 uppercase tracking-wider flex items-center gap-1.5">
                      <CheckCircle className="w-4.5 h-4.5" /> Positive habits
                    </h3>
                    <ul className="space-y-2 text-xs text-slate-600 dark:text-slate-350">
                      {selectedReport.positives.map((p, idx) => (
                        <li key={idx} className="flex gap-2 bg-emerald-500/5 border border-emerald-500/10 p-2.5 rounded-xl">
                          <span className="text-emerald-500">•</span>
                          <span>{parseBoldText(p)}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Mistakes / Problems */}
                  <div className="space-y-3">
                    <h3 className="text-sm font-extrabold text-rose-500 uppercase tracking-wider flex items-center gap-1.5">
                      <AlertTriangle className="w-4.5 h-4.5" /> Areas of concern
                    </h3>
                    <ul className="space-y-2 text-xs text-slate-600 dark:text-slate-350">
                      {selectedReport.mistakes.map((m, idx) => (
                        <li key={idx} className="flex gap-2 bg-rose-500/5 border border-rose-500/10 p-2.5 rounded-xl">
                          <span className="text-rose-500">•</span>
                          <span>{parseBoldText(m)}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Habits Detected (If Weekly/Monthly) */}
                {selectedReport.habitsDetected && selectedReport.habitsDetected.length > 0 && (
                  <div className="space-y-3 pt-4 border-t border-slate-200/50 dark:border-slate-800/40">
                    <h3 className="text-sm font-extrabold text-indigo-500 uppercase tracking-wider flex items-center gap-1.5">
                      <Brain className="w-4.5 h-4.5" /> Behavioral Patterns Detected
                    </h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                      {selectedReport.habitsDetected.map((h, idx) => (
                        <div key={idx} className="bg-indigo-500/5 border border-indigo-500/10 p-3 rounded-2xl text-xs text-slate-600 dark:text-slate-300 flex items-start gap-2">
                          <ArrowRight className="w-4 h-4 text-indigo-500 shrink-0 mt-0.5" />
                          <span>{parseBoldText(h)}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Recommendations */}
                <div className="space-y-3 pt-4 border-t border-slate-200/50 dark:border-slate-800/40">
                  <h3 className="text-sm font-extrabold text-amber-500 uppercase tracking-wider flex items-center gap-1.5">
                    <Lightbulb className="w-4.5 h-4.5" /> Recommendations
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                    {selectedReport.recommendations.map((r, idx) => (
                      <div key={idx} className="bg-amber-500/5 border border-amber-500/10 p-3.5 rounded-2xl text-xs text-slate-650 dark:text-slate-300 leading-relaxed">
                        <strong>Tip #{idx + 1}:</strong> {parseBoldText(r)}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="h-full flex items-center justify-center text-slate-450 text-sm">
              Please select a report or generate a new one to view AI analysis.
            </div>
          )}
        </div>

      </div>

      {/* Generator Modal */}
      <AnimatePresence>
        {showGenerator && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div 
              className="absolute inset-0 bg-black/60 backdrop-blur-sm" 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowGenerator(false)}
            />
            
            <motion.div 
              className="relative bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 w-full max-w-md p-6 rounded-2xl shadow-2xl overflow-hidden"
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
            >
              {generating ? (
                <div className="py-12 flex flex-col items-center justify-center space-y-5">
                  <div className="relative w-20 h-20">
                    <div className="absolute inset-0 border-4 border-indigo-500/20 rounded-full animate-ping" />
                    <div className="absolute inset-2 border-4 border-indigo-500/40 rounded-full animate-pulse" />
                    <div className="p-4 bg-indigo-600 text-white rounded-full flex items-center justify-center">
                      <Brain className="w-8 h-8 animate-bounce" />
                    </div>
                  </div>
                  <div className="text-center">
                    <h4 className="text-base font-bold text-slate-800 dark:text-white">Analyzing Health Logs</h4>
                    <p className="text-xs text-slate-400 mt-1 max-w-xs">
                      Correlating weight changes, identifying food patterns, and drafting recommendations...
                    </p>
                  </div>
                </div>
              ) : (
                <>
                  <h3 className="text-xl font-bold text-slate-800 dark:text-white mb-4 flex items-center gap-2">
                    <Brain className="w-5.5 h-5.5 text-indigo-500" /> Generate AI Audit
                  </h3>
                  
                  <form onSubmit={handleGenerate} className="space-y-4">
                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-slate-400 uppercase">Audit Timeframe</label>
                      <div className="grid grid-cols-3 gap-2">
                        {(['daily', 'weekly', 'monthly'] as const).map((t) => (
                          <button
                            key={t}
                            type="button"
                            onClick={() => setGenType(t)}
                            className={`text-xs capitalize py-2.5 rounded-xl font-bold border transition-all ${
                              genType === t 
                                ? 'bg-indigo-500/10 border-indigo-500 text-indigo-600 dark:text-indigo-400' 
                                : 'border-slate-200 dark:border-slate-800 text-slate-400 hover:text-slate-600'
                            }`}
                          >
                            {t}
                          </button>
                        ))}
                      </div>
                    </div>

                    <div className="space-y-1.5">
                      <label className="text-xs font-bold text-slate-400 uppercase">End Date for Audit</label>
                      <input
                        type="date"
                        required
                        value={genDate}
                        onChange={(e) => setGenDate(e.target.value)}
                        className="w-full glass-input"
                      />
                    </div>

                    <div className="flex gap-3 pt-2">
                      <button 
                        type="button"
                        onClick={() => setShowGenerator(false)}
                        className="flex-1 glass-btn-secondary"
                      >
                        Cancel
                      </button>
                      <button 
                        type="submit"
                        className="flex-1 glass-btn-primary"
                      >
                        Generate Audit
                      </button>
                    </div>
                  </form>
                </>
              )}
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};
